version: '3'
services:
  dev:
    restart: always
    tty: true
    depends_on:
      - redis
      - mysql
    build:
      context: .
      args:
        email: jacksonwu1992@sina.com
        user: jacksontwu
    ports:
      - '5000:5000'
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
      - ./redis.conf:/etc/redis/redis.conf
  mysql:
    image: mysql:5.7.22
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initd.d/
